openapi: '3.0.0'

info:
  title: Blueprint schema
  version: '1.0'
  description: |
    Image Builder Blueprint
    
    WORK IN PROGRESS
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Red Hat Image Builder Team
    url: 'https://osbuild.org'

components:
  schemas:
    Blueprint:
      $ref: ./components/blueprint.yaml
    error:
      type: object
      properties:
        error:
          type: string

paths:
  /validate_blueprint:
    post:
      summary: Validate blueprint
      operationId: validateBlueprint
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Blueprint"
              nullable: true
      responses:
        '201':
          description: The blueprint is valid
        '500':
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

servers:
  - url: https://osbuild.org/wip/api/v1
    description: Production server
