openapi: '3.0.0'

info:
  title: Blueprint schema
  version: '1.0'
  description: |
    Image Builder Blueprint
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Red Hat Image Builder Team
    url: 'https://osbuild.org'

components:
  schemas:
    # top-level components must not have underscores in their names
    blueprint:
      $ref: ./components/0_blueprint.yaml
    build_options: 
      $ref: ./components/0_build_options.yaml
    error:
      type: object
      properties:
        error:
          type: string

paths:
  /validate:
    post:
      summary: Validate
      operationId: validate
      requestBody:
        content:
          application/json:
            schema:
              properties:
                blueprint:
                  $ref: "#/components/schemas/blueprint"
                build_options:
                  $ref: "#/components/schemas/build_options"
      responses:
        '201':
          description: The blueprint is valid
        '500':
          description: An error occurred
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

servers:
  - url: https://osbuild.org/wip/api/v1
    description: Production server
