/*
Blueprint schema

Image Builder Blueprint  WORK IN PROGRESS 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BlueprintInstallerCoreos type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintInstallerCoreos{}

// BlueprintInstallerCoreos struct for BlueprintInstallerCoreos
type BlueprintInstallerCoreos struct {
	// Installation device for iot/edge simplified installer image types.
	InstallationDevice *string `json:"installation_device,omitempty"`
}

// NewBlueprintInstallerCoreos instantiates a new BlueprintInstallerCoreos object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintInstallerCoreos() *BlueprintInstallerCoreos {
	this := BlueprintInstallerCoreos{}
	return &this
}

// NewBlueprintInstallerCoreosWithDefaults instantiates a new BlueprintInstallerCoreos object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintInstallerCoreosWithDefaults() *BlueprintInstallerCoreos {
	this := BlueprintInstallerCoreos{}
	return &this
}

// GetInstallationDevice returns the InstallationDevice field value if set, zero value otherwise.
func (o *BlueprintInstallerCoreos) GetInstallationDevice() string {
	if o == nil || IsNil(o.InstallationDevice) {
		var ret string
		return ret
	}
	return *o.InstallationDevice
}

// GetInstallationDeviceOk returns a tuple with the InstallationDevice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintInstallerCoreos) GetInstallationDeviceOk() (*string, bool) {
	if o == nil || IsNil(o.InstallationDevice) {
		return nil, false
	}
	return o.InstallationDevice, true
}

// HasInstallationDevice returns a boolean if a field has been set.
func (o *BlueprintInstallerCoreos) HasInstallationDevice() bool {
	if o != nil && !IsNil(o.InstallationDevice) {
		return true
	}

	return false
}

// SetInstallationDevice gets a reference to the given string and assigns it to the InstallationDevice field.
func (o *BlueprintInstallerCoreos) SetInstallationDevice(v string) {
	o.InstallationDevice = &v
}

func (o BlueprintInstallerCoreos) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintInstallerCoreos) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstallationDevice) {
		toSerialize["installation_device"] = o.InstallationDevice
	}
	return toSerialize, nil
}

type NullableBlueprintInstallerCoreos struct {
	value *BlueprintInstallerCoreos
	isSet bool
}

func (v NullableBlueprintInstallerCoreos) Get() *BlueprintInstallerCoreos {
	return v.value
}

func (v *NullableBlueprintInstallerCoreos) Set(val *BlueprintInstallerCoreos) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintInstallerCoreos) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintInstallerCoreos) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintInstallerCoreos(val *BlueprintInstallerCoreos) *NullableBlueprintInstallerCoreos {
	return &NullableBlueprintInstallerCoreos{value: val, isSet: true}
}

func (v NullableBlueprintInstallerCoreos) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintInstallerCoreos) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


