/*
Blueprint schema

Image Builder Blueprint  WORK IN PROGRESS 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BlueprintFsnodesInnerContents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintFsnodesInnerContents{}

// BlueprintFsnodesInnerContents struct for BlueprintFsnodesInnerContents
type BlueprintFsnodesInnerContents struct {
	// Base64-encoded file contents. Useful for binaries.
	Base64 *string `json:"base64,omitempty"`
	// Plain text file contents.
	Text *string `json:"text,omitempty"`
}

// NewBlueprintFsnodesInnerContents instantiates a new BlueprintFsnodesInnerContents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintFsnodesInnerContents() *BlueprintFsnodesInnerContents {
	this := BlueprintFsnodesInnerContents{}
	return &this
}

// NewBlueprintFsnodesInnerContentsWithDefaults instantiates a new BlueprintFsnodesInnerContents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintFsnodesInnerContentsWithDefaults() *BlueprintFsnodesInnerContents {
	this := BlueprintFsnodesInnerContents{}
	return &this
}

// GetBase64 returns the Base64 field value if set, zero value otherwise.
func (o *BlueprintFsnodesInnerContents) GetBase64() string {
	if o == nil || IsNil(o.Base64) {
		var ret string
		return ret
	}
	return *o.Base64
}

// GetBase64Ok returns a tuple with the Base64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintFsnodesInnerContents) GetBase64Ok() (*string, bool) {
	if o == nil || IsNil(o.Base64) {
		return nil, false
	}
	return o.Base64, true
}

// HasBase64 returns a boolean if a field has been set.
func (o *BlueprintFsnodesInnerContents) HasBase64() bool {
	if o != nil && !IsNil(o.Base64) {
		return true
	}

	return false
}

// SetBase64 gets a reference to the given string and assigns it to the Base64 field.
func (o *BlueprintFsnodesInnerContents) SetBase64(v string) {
	o.Base64 = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *BlueprintFsnodesInnerContents) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintFsnodesInnerContents) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *BlueprintFsnodesInnerContents) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *BlueprintFsnodesInnerContents) SetText(v string) {
	o.Text = &v
}

func (o BlueprintFsnodesInnerContents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintFsnodesInnerContents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Base64) {
		toSerialize["base64"] = o.Base64
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableBlueprintFsnodesInnerContents struct {
	value *BlueprintFsnodesInnerContents
	isSet bool
}

func (v NullableBlueprintFsnodesInnerContents) Get() *BlueprintFsnodesInnerContents {
	return v.value
}

func (v *NullableBlueprintFsnodesInnerContents) Set(val *BlueprintFsnodesInnerContents) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintFsnodesInnerContents) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintFsnodesInnerContents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintFsnodesInnerContents(val *BlueprintFsnodesInnerContents) *NullableBlueprintFsnodesInnerContents {
	return &NullableBlueprintFsnodesInnerContents{value: val, isSet: true}
}

func (v NullableBlueprintFsnodesInnerContents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintFsnodesInnerContents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


