/*
Blueprint schema

Image Builder Blueprint  WORK IN PROGRESS 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BlueprintNetworkFirewallServicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintNetworkFirewallServicesInner{}

// BlueprintNetworkFirewallServicesInner struct for BlueprintNetworkFirewallServicesInner
type BlueprintNetworkFirewallServicesInner struct {
	Enabled NullableBool
	From *int32
	Port *int32
	Protocol *string
	Service *string
	To *int32
}

// NewBlueprintNetworkFirewallServicesInner instantiates a new BlueprintNetworkFirewallServicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintNetworkFirewallServicesInner() *BlueprintNetworkFirewallServicesInner {
	this := BlueprintNetworkFirewallServicesInner{}
	return &this
}

// NewBlueprintNetworkFirewallServicesInnerWithDefaults instantiates a new BlueprintNetworkFirewallServicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintNetworkFirewallServicesInnerWithDefaults() *BlueprintNetworkFirewallServicesInner {
	this := BlueprintNetworkFirewallServicesInner{}
	var protocol string = "any"
	this.Protocol = &protocol
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlueprintNetworkFirewallServicesInner) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled.Get()) {
		var ret bool
		return ret
	}
	return *o.Enabled.Get()
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlueprintNetworkFirewallServicesInner) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Enabled.Get(), o.Enabled.IsSet()
}

// HasEnabled returns a boolean if a field has been set.
func (o *BlueprintNetworkFirewallServicesInner) HasEnabled() bool {
	if o != nil && o.Enabled.IsSet() {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given NullableBool and assigns it to the Enabled field.
func (o *BlueprintNetworkFirewallServicesInner) SetEnabled(v bool) {
	o.Enabled.Set(&v)
}
// SetEnabledNil sets the value for Enabled to be an explicit nil
func (o *BlueprintNetworkFirewallServicesInner) SetEnabledNil() {
	o.Enabled.Set(nil)
}

// UnsetEnabled ensures that no value is present for Enabled, not even an explicit nil
func (o *BlueprintNetworkFirewallServicesInner) UnsetEnabled() {
	o.Enabled.Unset()
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *BlueprintNetworkFirewallServicesInner) GetFrom() int32 {
	if o == nil || IsNil(o.From) {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintNetworkFirewallServicesInner) GetFromOk() (*int32, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *BlueprintNetworkFirewallServicesInner) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *BlueprintNetworkFirewallServicesInner) SetFrom(v int32) {
	o.From = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *BlueprintNetworkFirewallServicesInner) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintNetworkFirewallServicesInner) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *BlueprintNetworkFirewallServicesInner) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *BlueprintNetworkFirewallServicesInner) SetPort(v int32) {
	o.Port = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *BlueprintNetworkFirewallServicesInner) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintNetworkFirewallServicesInner) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *BlueprintNetworkFirewallServicesInner) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *BlueprintNetworkFirewallServicesInner) SetProtocol(v string) {
	o.Protocol = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *BlueprintNetworkFirewallServicesInner) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintNetworkFirewallServicesInner) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *BlueprintNetworkFirewallServicesInner) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *BlueprintNetworkFirewallServicesInner) SetService(v string) {
	o.Service = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *BlueprintNetworkFirewallServicesInner) GetTo() int32 {
	if o == nil || IsNil(o.To) {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintNetworkFirewallServicesInner) GetToOk() (*int32, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *BlueprintNetworkFirewallServicesInner) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *BlueprintNetworkFirewallServicesInner) SetTo(v int32) {
	o.To = &v
}

func (o BlueprintNetworkFirewallServicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintNetworkFirewallServicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Enabled.IsSet() {
		toSerialize["enabled"] = o.Enabled.Get()
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableBlueprintNetworkFirewallServicesInner struct {
	value *BlueprintNetworkFirewallServicesInner
	isSet bool
}

func (v NullableBlueprintNetworkFirewallServicesInner) Get() *BlueprintNetworkFirewallServicesInner {
	return v.value
}

func (v *NullableBlueprintNetworkFirewallServicesInner) Set(val *BlueprintNetworkFirewallServicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintNetworkFirewallServicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintNetworkFirewallServicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintNetworkFirewallServicesInner(val *BlueprintNetworkFirewallServicesInner) *NullableBlueprintNetworkFirewallServicesInner {
	return &NullableBlueprintNetworkFirewallServicesInner{value: val, isSet: true}
}

func (v NullableBlueprintNetworkFirewallServicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintNetworkFirewallServicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


