/*
Blueprint schema

Image Builder Blueprint  WORK IN PROGRESS 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BlueprintRegistration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintRegistration{}

// BlueprintRegistration struct for BlueprintRegistration
type BlueprintRegistration struct {
	Fdo NullableBlueprintRegistrationFdo `json:"fdo,omitempty"`
	Redhat *BlueprintRegistrationRedhat `json:"redhat,omitempty"`
}

// NewBlueprintRegistration instantiates a new BlueprintRegistration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintRegistration() *BlueprintRegistration {
	this := BlueprintRegistration{}
	return &this
}

// NewBlueprintRegistrationWithDefaults instantiates a new BlueprintRegistration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintRegistrationWithDefaults() *BlueprintRegistration {
	this := BlueprintRegistration{}
	return &this
}

// GetFdo returns the Fdo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BlueprintRegistration) GetFdo() BlueprintRegistrationFdo {
	if o == nil || IsNil(o.Fdo.Get()) {
		var ret BlueprintRegistrationFdo
		return ret
	}
	return *o.Fdo.Get()
}

// GetFdoOk returns a tuple with the Fdo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BlueprintRegistration) GetFdoOk() (*BlueprintRegistrationFdo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fdo.Get(), o.Fdo.IsSet()
}

// HasFdo returns a boolean if a field has been set.
func (o *BlueprintRegistration) HasFdo() bool {
	if o != nil && o.Fdo.IsSet() {
		return true
	}

	return false
}

// SetFdo gets a reference to the given NullableBlueprintRegistrationFdo and assigns it to the Fdo field.
func (o *BlueprintRegistration) SetFdo(v BlueprintRegistrationFdo) {
	o.Fdo.Set(&v)
}
// SetFdoNil sets the value for Fdo to be an explicit nil
func (o *BlueprintRegistration) SetFdoNil() {
	o.Fdo.Set(nil)
}

// UnsetFdo ensures that no value is present for Fdo, not even an explicit nil
func (o *BlueprintRegistration) UnsetFdo() {
	o.Fdo.Unset()
}

// GetRedhat returns the Redhat field value if set, zero value otherwise.
func (o *BlueprintRegistration) GetRedhat() BlueprintRegistrationRedhat {
	if o == nil || IsNil(o.Redhat) {
		var ret BlueprintRegistrationRedhat
		return ret
	}
	return *o.Redhat
}

// GetRedhatOk returns a tuple with the Redhat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintRegistration) GetRedhatOk() (*BlueprintRegistrationRedhat, bool) {
	if o == nil || IsNil(o.Redhat) {
		return nil, false
	}
	return o.Redhat, true
}

// HasRedhat returns a boolean if a field has been set.
func (o *BlueprintRegistration) HasRedhat() bool {
	if o != nil && !IsNil(o.Redhat) {
		return true
	}

	return false
}

// SetRedhat gets a reference to the given BlueprintRegistrationRedhat and assigns it to the Redhat field.
func (o *BlueprintRegistration) SetRedhat(v BlueprintRegistrationRedhat) {
	o.Redhat = &v
}

func (o BlueprintRegistration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintRegistration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Fdo.IsSet() {
		toSerialize["fdo"] = o.Fdo.Get()
	}
	if !IsNil(o.Redhat) {
		toSerialize["redhat"] = o.Redhat
	}
	return toSerialize, nil
}

type NullableBlueprintRegistration struct {
	value *BlueprintRegistration
	isSet bool
}

func (v NullableBlueprintRegistration) Get() *BlueprintRegistration {
	return v.value
}

func (v *NullableBlueprintRegistration) Set(val *BlueprintRegistration) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintRegistration) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintRegistration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintRegistration(val *BlueprintRegistration) *NullableBlueprintRegistration {
	return &NullableBlueprintRegistration{value: val, isSet: true}
}

func (v NullableBlueprintRegistration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintRegistration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


