/*
Blueprint schema

Image Builder Blueprint  WORK IN PROGRESS 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BlueprintNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintNetwork{}

// BlueprintNetwork struct for BlueprintNetwork
type BlueprintNetwork struct {
	Firewall *BlueprintNetworkFirewall `json:"firewall,omitempty"`
}

// NewBlueprintNetwork instantiates a new BlueprintNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintNetwork() *BlueprintNetwork {
	this := BlueprintNetwork{}
	return &this
}

// NewBlueprintNetworkWithDefaults instantiates a new BlueprintNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintNetworkWithDefaults() *BlueprintNetwork {
	this := BlueprintNetwork{}
	return &this
}

// GetFirewall returns the Firewall field value if set, zero value otherwise.
func (o *BlueprintNetwork) GetFirewall() BlueprintNetworkFirewall {
	if o == nil || IsNil(o.Firewall) {
		var ret BlueprintNetworkFirewall
		return ret
	}
	return *o.Firewall
}

// GetFirewallOk returns a tuple with the Firewall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintNetwork) GetFirewallOk() (*BlueprintNetworkFirewall, bool) {
	if o == nil || IsNil(o.Firewall) {
		return nil, false
	}
	return o.Firewall, true
}

// HasFirewall returns a boolean if a field has been set.
func (o *BlueprintNetwork) HasFirewall() bool {
	if o != nil && !IsNil(o.Firewall) {
		return true
	}

	return false
}

// SetFirewall gets a reference to the given BlueprintNetworkFirewall and assigns it to the Firewall field.
func (o *BlueprintNetwork) SetFirewall(v BlueprintNetworkFirewall) {
	o.Firewall = &v
}

func (o BlueprintNetwork) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Firewall) {
		toSerialize["firewall"] = o.Firewall
	}
	return toSerialize, nil
}

type NullableBlueprintNetwork struct {
	value *BlueprintNetwork
	isSet bool
}

func (v NullableBlueprintNetwork) Get() *BlueprintNetwork {
	return v.value
}

func (v *NullableBlueprintNetwork) Set(val *BlueprintNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintNetwork(val *BlueprintNetwork) *NullableBlueprintNetwork {
	return &NullableBlueprintNetwork{value: val, isSet: true}
}

func (v NullableBlueprintNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


