/*
Blueprint schema

Image Builder Blueprint  WORK IN PROGRESS 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlueprintRegistrationRedhatConnector type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintRegistrationRedhatConnector{}

// BlueprintRegistrationRedhatConnector struct for BlueprintRegistrationRedhatConnector
type BlueprintRegistrationRedhatConnector struct {
	// Enables rhc (Red Hat Connector) during boot.
	Enabled bool `json:"enabled"`
}

type _BlueprintRegistrationRedhatConnector BlueprintRegistrationRedhatConnector

// NewBlueprintRegistrationRedhatConnector instantiates a new BlueprintRegistrationRedhatConnector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintRegistrationRedhatConnector(enabled bool) *BlueprintRegistrationRedhatConnector {
	this := BlueprintRegistrationRedhatConnector{}
	this.Enabled = enabled
	return &this
}

// NewBlueprintRegistrationRedhatConnectorWithDefaults instantiates a new BlueprintRegistrationRedhatConnector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintRegistrationRedhatConnectorWithDefaults() *BlueprintRegistrationRedhatConnector {
	this := BlueprintRegistrationRedhatConnector{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *BlueprintRegistrationRedhatConnector) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *BlueprintRegistrationRedhatConnector) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *BlueprintRegistrationRedhatConnector) SetEnabled(v bool) {
	o.Enabled = v
}

func (o BlueprintRegistrationRedhatConnector) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintRegistrationRedhatConnector) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *BlueprintRegistrationRedhatConnector) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlueprintRegistrationRedhatConnector := _BlueprintRegistrationRedhatConnector{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlueprintRegistrationRedhatConnector)

	if err != nil {
		return err
	}

	*o = BlueprintRegistrationRedhatConnector(varBlueprintRegistrationRedhatConnector)

	return err
}

type NullableBlueprintRegistrationRedhatConnector struct {
	value *BlueprintRegistrationRedhatConnector
	isSet bool
}

func (v NullableBlueprintRegistrationRedhatConnector) Get() *BlueprintRegistrationRedhatConnector {
	return v.value
}

func (v *NullableBlueprintRegistrationRedhatConnector) Set(val *BlueprintRegistrationRedhatConnector) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintRegistrationRedhatConnector) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintRegistrationRedhatConnector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintRegistrationRedhatConnector(val *BlueprintRegistrationRedhatConnector) *NullableBlueprintRegistrationRedhatConnector {
	return &NullableBlueprintRegistrationRedhatConnector{value: val, isSet: true}
}

func (v NullableBlueprintRegistrationRedhatConnector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintRegistrationRedhatConnector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


