/*
Blueprint schema

Image Builder Blueprint  WORK IN PROGRESS 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlueprintRegistrationFdo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlueprintRegistrationFdo{}

// BlueprintRegistrationFdo struct for BlueprintRegistrationFdo
type BlueprintRegistrationFdo struct {
	// Optional interface name for the MAC address.
	DiMfgStringTypeMacIface *string
	// FDO server public key hex-encoded hash. Cannot be used together with insecure option or root certs.
	DiunPubKeyHash *string
	// FDO insecure option. When set, both hash or root certs must not be set.
	DiunPubKeyInsecure *bool
	// FDO server public key root certificate path. Cannot be used together with insecure option or hash.
	DiunPubKeyRootCerts *string
	// FDO manufacturing server URL.
	ManufacturingServerUrl string
}

type _BlueprintRegistrationFdo BlueprintRegistrationFdo

// NewBlueprintRegistrationFdo instantiates a new BlueprintRegistrationFdo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlueprintRegistrationFdo(manufacturingServerUrl string) *BlueprintRegistrationFdo {
	this := BlueprintRegistrationFdo{}
	return &this
}

// NewBlueprintRegistrationFdoWithDefaults instantiates a new BlueprintRegistrationFdo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlueprintRegistrationFdoWithDefaults() *BlueprintRegistrationFdo {
	this := BlueprintRegistrationFdo{}
	var diunPubKeyInsecure bool = false
	this.DiunPubKeyInsecure = &diunPubKeyInsecure
	return &this
}

// GetDiMfgStringTypeMacIface returns the DiMfgStringTypeMacIface field value if set, zero value otherwise.
func (o *BlueprintRegistrationFdo) GetDiMfgStringTypeMacIface() string {
	if o == nil || IsNil(o.DiMfgStringTypeMacIface) {
		var ret string
		return ret
	}
	return *o.DiMfgStringTypeMacIface
}

// GetDiMfgStringTypeMacIfaceOk returns a tuple with the DiMfgStringTypeMacIface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintRegistrationFdo) GetDiMfgStringTypeMacIfaceOk() (*string, bool) {
	if o == nil || IsNil(o.DiMfgStringTypeMacIface) {
		return nil, false
	}
	return o.DiMfgStringTypeMacIface, true
}

// HasDiMfgStringTypeMacIface returns a boolean if a field has been set.
func (o *BlueprintRegistrationFdo) HasDiMfgStringTypeMacIface() bool {
	if o != nil && !IsNil(o.DiMfgStringTypeMacIface) {
		return true
	}

	return false
}

// SetDiMfgStringTypeMacIface gets a reference to the given string and assigns it to the DiMfgStringTypeMacIface field.
func (o *BlueprintRegistrationFdo) SetDiMfgStringTypeMacIface(v string) {
	o.DiMfgStringTypeMacIface = &v
}

// GetDiunPubKeyHash returns the DiunPubKeyHash field value if set, zero value otherwise.
func (o *BlueprintRegistrationFdo) GetDiunPubKeyHash() string {
	if o == nil || IsNil(o.DiunPubKeyHash) {
		var ret string
		return ret
	}
	return *o.DiunPubKeyHash
}

// GetDiunPubKeyHashOk returns a tuple with the DiunPubKeyHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintRegistrationFdo) GetDiunPubKeyHashOk() (*string, bool) {
	if o == nil || IsNil(o.DiunPubKeyHash) {
		return nil, false
	}
	return o.DiunPubKeyHash, true
}

// HasDiunPubKeyHash returns a boolean if a field has been set.
func (o *BlueprintRegistrationFdo) HasDiunPubKeyHash() bool {
	if o != nil && !IsNil(o.DiunPubKeyHash) {
		return true
	}

	return false
}

// SetDiunPubKeyHash gets a reference to the given string and assigns it to the DiunPubKeyHash field.
func (o *BlueprintRegistrationFdo) SetDiunPubKeyHash(v string) {
	o.DiunPubKeyHash = &v
}

// GetDiunPubKeyInsecure returns the DiunPubKeyInsecure field value if set, zero value otherwise.
func (o *BlueprintRegistrationFdo) GetDiunPubKeyInsecure() bool {
	if o == nil || IsNil(o.DiunPubKeyInsecure) {
		var ret bool
		return ret
	}
	return *o.DiunPubKeyInsecure
}

// GetDiunPubKeyInsecureOk returns a tuple with the DiunPubKeyInsecure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintRegistrationFdo) GetDiunPubKeyInsecureOk() (*bool, bool) {
	if o == nil || IsNil(o.DiunPubKeyInsecure) {
		return nil, false
	}
	return o.DiunPubKeyInsecure, true
}

// HasDiunPubKeyInsecure returns a boolean if a field has been set.
func (o *BlueprintRegistrationFdo) HasDiunPubKeyInsecure() bool {
	if o != nil && !IsNil(o.DiunPubKeyInsecure) {
		return true
	}

	return false
}

// SetDiunPubKeyInsecure gets a reference to the given bool and assigns it to the DiunPubKeyInsecure field.
func (o *BlueprintRegistrationFdo) SetDiunPubKeyInsecure(v bool) {
	o.DiunPubKeyInsecure = &v
}

// GetDiunPubKeyRootCerts returns the DiunPubKeyRootCerts field value if set, zero value otherwise.
func (o *BlueprintRegistrationFdo) GetDiunPubKeyRootCerts() string {
	if o == nil || IsNil(o.DiunPubKeyRootCerts) {
		var ret string
		return ret
	}
	return *o.DiunPubKeyRootCerts
}

// GetDiunPubKeyRootCertsOk returns a tuple with the DiunPubKeyRootCerts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlueprintRegistrationFdo) GetDiunPubKeyRootCertsOk() (*string, bool) {
	if o == nil || IsNil(o.DiunPubKeyRootCerts) {
		return nil, false
	}
	return o.DiunPubKeyRootCerts, true
}

// HasDiunPubKeyRootCerts returns a boolean if a field has been set.
func (o *BlueprintRegistrationFdo) HasDiunPubKeyRootCerts() bool {
	if o != nil && !IsNil(o.DiunPubKeyRootCerts) {
		return true
	}

	return false
}

// SetDiunPubKeyRootCerts gets a reference to the given string and assigns it to the DiunPubKeyRootCerts field.
func (o *BlueprintRegistrationFdo) SetDiunPubKeyRootCerts(v string) {
	o.DiunPubKeyRootCerts = &v
}

// GetManufacturingServerUrl returns the ManufacturingServerUrl field value
func (o *BlueprintRegistrationFdo) GetManufacturingServerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManufacturingServerUrl
}

// GetManufacturingServerUrlOk returns a tuple with the ManufacturingServerUrl field value
// and a boolean to check if the value has been set.
func (o *BlueprintRegistrationFdo) GetManufacturingServerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManufacturingServerUrl, true
}

// SetManufacturingServerUrl sets field value
func (o *BlueprintRegistrationFdo) SetManufacturingServerUrl(v string) {
	o.ManufacturingServerUrl = v
}

func (o BlueprintRegistrationFdo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlueprintRegistrationFdo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DiMfgStringTypeMacIface) {
		toSerialize["di_mfg_string_type_mac_iface"] = o.DiMfgStringTypeMacIface
	}
	if !IsNil(o.DiunPubKeyHash) {
		toSerialize["diun_pub_key_hash"] = o.DiunPubKeyHash
	}
	if !IsNil(o.DiunPubKeyInsecure) {
		toSerialize["diun_pub_key_insecure"] = o.DiunPubKeyInsecure
	}
	if !IsNil(o.DiunPubKeyRootCerts) {
		toSerialize["diun_pub_key_root_certs"] = o.DiunPubKeyRootCerts
	}
	toSerialize["manufacturing_server_url"] = o.ManufacturingServerUrl
	return toSerialize, nil
}

func (o *BlueprintRegistrationFdo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"manufacturing_server_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlueprintRegistrationFdo := _BlueprintRegistrationFdo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlueprintRegistrationFdo)

	if err != nil {
		return err
	}

	*o = BlueprintRegistrationFdo(varBlueprintRegistrationFdo)

	return err
}

type NullableBlueprintRegistrationFdo struct {
	value *BlueprintRegistrationFdo
	isSet bool
}

func (v NullableBlueprintRegistrationFdo) Get() *BlueprintRegistrationFdo {
	return v.value
}

func (v *NullableBlueprintRegistrationFdo) Set(val *BlueprintRegistrationFdo) {
	v.value = val
	v.isSet = true
}

func (v NullableBlueprintRegistrationFdo) IsSet() bool {
	return v.isSet
}

func (v *NullableBlueprintRegistrationFdo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlueprintRegistrationFdo(val *BlueprintRegistrationFdo) *NullableBlueprintRegistrationFdo {
	return &NullableBlueprintRegistrationFdo{value: val, isSet: true}
}

func (v NullableBlueprintRegistrationFdo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlueprintRegistrationFdo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


