name: linters

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: "Linters"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --config=.golangci.yaml

      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: oas/
