name: Make github release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: read

# TinyGo is only compatible with specific Go vesions:
#   https://github.com/tinygo-org/tinygo/releases
env:
  GO_VERSION: 1.23.0 
  TINYGO_VERSION: 0.36.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: ${{ env.TINYGO_VERSION }}

      - name: Build
        run: make -j build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            name: v0.0.0
            draft: true
            files: dist/*
