name: tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  merge_group:

jobs:
  lint:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - uses: actions/checkout@v4

      - name: Build schema and run tests
        run: |
          make schema write-fixtures test test-diff

      - name: Check for code generation changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo
            echo "Code was not generated, diff of the first 5k lines:"
            git status -vv | head -n5000
            exit "1"
          else
            exit "0"
          fi
